In [2]:
from sklearn.datasets import load_boston
import matplotlib.pyplot as plt
boston = load_boston()
x = boston.data
y = boston.target
print(x.shape)
print(y.shape)
print(boston.DESCR)
print(type(boston))
plt.hist(y, bins=30, color='b', density=True, stacked=True)

ImportError:
`load_boston` has been removed from scikit-learn since version 1.2.

The Boston housing prices dataset has an ethical problem: as
investigated in [1], the authors of this dataset engineered a
non-invertible variable "B" assuming that racial self-segregation had a
positive impact on house prices [2]. Furthermore the goal of the
research that led to the creation of this dataset was to study the
impact of air quality but it did not give adequate demonstration of the
validity of this assumption.

The scikit-learn maintainers therefore strongly discourage the use of
this dataset unless the purpose of the code is to study and educate
about ethical issues in data science and machine learning.

In this special case, you can fetch the dataset from the original
source::

    import pandas as pd
    import numpy as np

    data_url = "http://lib.stat.cmu.edu/datasets/boston"
    raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
    data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
    target = raw_df.values[1::2, 2]

Alternative datasets include the California housing dataset and the
Ames housing dataset. You can load the datasets as follows::

    from sklearn.datasets import fetch_california_housing
    housing = fetch_california_housing()

for the California housing dataset and::

    from sklearn.datasets import fetch_openml
    housing = fetch_openml(name="house_prices", as_frame=True)

for the Ames housing dataset.

[1] M Carlisle.
"Racist data destruction?"
<https://medium.com/@docintangible/racist-data-destruction-113e3eff54a8>

[2] Harrison Jr, David, and Daniel L. Rubinfeld.
"Hedonic housing prices and the demand for clean air."
Journal of environmental economics and management 5.1 (1978): 81-102.
<https://www.researchgate.net/publication/4974606_Hedonic_housing_prices_and_the_demand_for_clean_air>

# Masked Face Detection
## Pre-Processing

# TMDB 5000 Dataset
## Pre-Processing

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import datasets
import json

tmdbCredits = pd.read_csv("tmdb_5000_credits.csv")
tmdbMovies = pd.read_csv("tmdb_5000_movies.csv")

tmdbCredits.head()

print(tmdbCredits['crew'])
#print(tmdbMovies.describe())
#print(type(boston))
#plt.hist(y, bins=30, color='b', density=True, stacked=True)

0       [{"credit_id": "52fe48009251416c750aca23", "de...
1       [{"credit_id": "52fe4232c3a36847f800b579", "de...
2       [{"credit_id": "54805967c3a36829b5002c41", "de...
3       [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4       [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
                              ...
4798    [{"credit_id": "52fe44eec3a36847f80b280b", "de...
4799    [{"credit_id": "52fe487dc3a368484e0fb013", "de...
4800    [{"credit_id": "52fe4df3c3a36847f8275ecf", "de...
4801    [{"credit_id": "52fe4ad9c3a368484e16a36b", "de...
4802    [{"credit_id": "58ce021b9251415a390165d9", "de...
Name: crew, Length: 4803, dtype: object

In [2]:
tmdbMovies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [3]:
tmdbCredits.columns = ['id','title','cast','crew']
tmdb = tmdbMovies.merge(tmdbCredits, on='id')
tmdb = tmdb.drop(['title_y','title_x','homepage','tagline', 
                  'id', 'budget', 'revenue', 'status','spoken_languages', 
                  'original_language', 'overview', 'production_companies', 
                  'production_countries', 'runtime'], axis=1)

In [4]:
tmdb.dtypes

genres             object
keywords           object
original_title     object
popularity        float64
release_date       object
vote_average      float64
vote_count          int64
cast               object
crew               object
dtype: object

In [15]:
tmdb.count()

genres            4775
keywords          4803
original_title    4803
popularity        4803
release_date      4802
vote_average      4803
vote_count        4803
actor_1           4803
actor_2           4803
actor_3           4803
director          4773
producer          3780
editor            3564
dtype: int64

In [6]:
dict_columns = ['genres','keywords','cast','crew']
for column in dict_columns:   
    tmdb[column] = tmdb[column].apply(json.loads)

In [10]:
def extract_genres(genre_info):
    genres = []
    for genre in genre_info:
        genres.append(genre['name'])
    if len(genres) == 0:
        return np.nan
    else:
        return genres
    

tmdb['genres'] = tmdb['genres'].apply(extract_genres)

In [11]:
def extract_actor(cast_info, order):
    for cast_member in cast_info:
        if cast_member['order'] == order:
            return cast_member['name']
    return ''

tmdb['actor_1'] = tmdb['cast'].apply(extract_actor, order=0)
tmdb['actor_2'] = tmdb['cast'].apply(extract_actor, order=1)
tmdb['actor_3'] = tmdb['cast'].apply(extract_actor, order=2)

tmdb = tmdb.drop(['cast'], axis=1)

In [12]:
def extract_cast(crew_info, job):
    cast = []
    for crew_member in crew_info:
        if crew_member['job'] == job:
            cast.append(crew_member['name'])
    if len(cast) == 0:
        return np.nan
    else:
        return cast

tmdb['director'] = tmdb['crew'].apply(extract_cast, job='Director')
tmdb['producer'] = tmdb['crew'].apply(extract_cast, job='Producer')
tmdb['editor'] = tmdb['crew'].apply(extract_cast, job='Editor')

tmdb = tmdb.drop(['crew'], axis=1)

In [13]:
tmdb['keywords'][7]

[{'id': 8828, 'name': 'marvel comic'},
 {'id': 9663, 'name': 'sequel'},
 {'id': 9715, 'name': 'superhero'},
 {'id': 9717, 'name': 'based on comic book'},
 {'id': 10629, 'name': 'vision'},
 {'id': 155030, 'name': 'superhero team'},
 {'id': 179431, 'name': 'duringcreditsstinger'},
 {'id': 180547, 'name': 'marvel cinematic universe'},
 {'id': 209714, 'name': '3d'}]

In [14]:
tmdb.head(20)

,genres,keywords,original_title,popularity,release_date,vote_average,vote_count,actor_1,actor_2,actor_3,director,producer,editor
0,"[Action, Adventure, Fantasy, Science Fiction]","[{'id': 1463, 'name': 'culture clash'}, {'id':...",Avatar,150.437577,2009-12-10,7.2,11800,Sam Worthington,Zoe Saldana,Sigourney Weaver,[James Cameron],"[James Cameron, Jon Landau]","[Stephen E. Rivkin, James Cameron, John Refoua]"
1,"[Adventure, Fantasy, Action]","[{'id': 270, 'name': 'ocean'}, {'id': 726, 'na...",Pirates of the Caribbean: At World's End,139.082615,2007-05-19,6.9,4500,Johnny Depp,Orlando Bloom,Keira Knightley,[Gore Verbinski],"[Jerry Bruckheimer, Eric McLeod, Chad Oman, Pe...","[Stephen E. Rivkin, Craig Wood]"
2,"[Action, Adventure, Crime]","[{'id': 470, 'name': 'spy'}, {'id': 818, 'name...",Spectre,107.376788,2015-10-26,6.3,4466,Daniel Craig,Christoph Waltz,Léa Seydoux,[Sam Mendes],"[Barbara Broccoli, Michael G. Wilson]",[Lee Smith]
3,"[Action, Crime, Drama, Thriller]","[{'id': 849, 'name': 'dc comics'}, {'id': 853,...",The Dark Knight Rises,112.312950,2012-07-16,7.6,9106,Christian Bale,Michael Caine,Gary Oldman,[Christopher Nolan],"[Charles Roven, Christopher Nolan, Emma Thomas]",[Lee Smith]
4,"[Action, Adventure, Science Fiction]","[{'id': 818, 'name': 'based on novel'}, {'id':...",John Carter,43.926995,2012-03-07,6.1,2124,Taylor Kitsch,Lynn Collins,Samantha Morton,[Andrew Stanton],"[Colin Wilson, Jim Morris, Lindsey Collins]",[Eric Zumbrunnen]
5,"[Fantasy, Action, Adventure]","[{'id': 851, 'name': 'dual identity'}, {'id': ...",Spider-Man 3,115.699814,2007-05-01,5.9,3576,Tobey Maguire,Kirsten Dunst,James Franco,[Sam Raimi],"[Laura Ziskin, Avi Arad, Grant Curtis]",[Bob Murawski]
6,"[Animation, Family]","[{'id': 1562, 'name': 'hostage'}, {'id': 2343,...",Tangled,48.681969,2010-11-24,7.4,3330,Zachary Levi,Mandy Moore,Donna Murphy,"[Byron Howard, Nathan Greno]",[Roy Conli],[Tim Mertens]
7,"[Action, Adventure, Science Fiction]","[{'id': 8828, 'name': 'marvel comic'}, {'id': ...",Avengers: Age of Ultron,134.279229,2015-04-22,7.3,6767,Robert Downey Jr.,Chris Hemsworth,Mark Ruffalo,[Joss Whedon],[Kevin Feige],"[Jeffrey Ford, Lisa Lassek]"
8,"[Adventure, Fantasy, Family]","[{'id': 616, 'name': 'witch'}, {'id': 2343, 'n...",Harry Potter and the Half-Blood Prince,98.885637,2009-07-07,7.4,5293,Daniel Radcliffe,Rupert Grint,Emma Watson,[David Yates],"[David Heyman, David Barron, Tim Lewis]",[Mark Day]
9,"[Action, Adventure, Fantasy]","[{'id': 849, 'name': 'dc comics'}, {'id': 7002...",Batman v Superman: Dawn of Justice,155.790452,2016-03-23,5.7,7004,Ben Affleck,Henry Cavill,Gal Gadot,[Zack Snyder],"[Charles Roven, Deborah Snyder]",[David Brenner]
10,"[Adventure, Fantasy, Action, Science Fiction]","[{'id': 83, 'name': 'saving the world'}, {'id'...",Superman Returns,57.925623,2006-06-28,5.4,1400,Brandon Routh,Kevin Spacey,Kate Bosworth,[Bryan Singer],"[Jon Peters, Gilbert Adler, Bryan Singer]","[John Ottman, Elliot Graham]"
11,"[Adventure, Action, Thriller, Crime]","[{'id': 627, 'name': 'killing'}, {'id': 1568, ...",Quantum of Solace,107.928811,2008-10-30,6.1,2965,Daniel Craig,Olga Kurylenko,Mathieu Amalric,[Marc Forster],"[Barbara Broccoli, Michael G. Wilson]","[Richard Pearson, Matt Chesse]"
12,"[Adventure, Fantasy, Action]","[{'id': 616, 'name': 'witch'}, {'id': 663, 'na...",Pirates of the Caribbean: Dead Man's Chest,145.847379,2006-06-20,7.0,5246,Johnny Depp,Orlando Bloom,Keira Knightley,[Gore Verbinski],"[Jerry Bruckheimer, Peter Kohn, Pat Sandston]","[Stephen E. Rivkin, Craig Wood]"
13,"[Action, Adventure, Western]","[{'id': 1556, 'name': 'texas'}, {'id': 2673, '...",The Lone Ranger,49.046956,2013-07-03,5.9,2311,Johnny Depp,Armie Hammer,William Fichtner,[Gore Verbinski],"[Gore Verbinski, Jerry Bruckheimer]","[Craig Wood, James Haygood]"
14,"[Action, Adventure, Fantasy, Science Fiction]","[{'id': 83, 'name': 'saving the world'}, {'id'...",Man of Steel,99.398009,2013-06-12,6.5,6359,Henry Cavill,Amy Adams,Michael Shannon,[Zack Snyder],"[Charles Roven, Christopher Nolan, Emma Thomas...",[David Brenner]
15,"[Adventure, Family, Fantasy]","[{'id': 818, 'name': 'based on novel'}, {'id':...",The Chronicles of Narnia: Prince Caspian,53.978602,2008-05-15,6.3,1630,Ben Barnes,William Moseley,Anna Popplewell,[Andrew Adamson],"[Mark Johnson, Andrew Adamson, Philip Steuer]","[Sim Evan-Jones, Josh Campbell]"
16,"[Science Fiction, Action, Adventure]","[{'id': 242, 'name': 'new york'}, {'id': 5539,...",The Avengers,144.448633,2012-04-25,7.4,11776,Robert Downey Jr.,Chris Evans,Mark Ruffalo,[Joss Whedon],[Kevin Feige],"[Jeffrey Ford, Lisa Lassek]"
17,"[Adventure, Action, Fantasy]","[{'id': 658, 'name': 'sea'}, {'id': 1316, 'nam...",Pirates of the Caribbean: On Stranger Tides,135.413856,2011-05-14,6.4,4948,Johnny Depp,Penélope Cruz,Ian McShane,[Rob Marshall],[Jerry Bruckheimer],"[David Brenner, Wyatt Smith]"
18,"[Action, Comedy, Science Fiction]","[{'id': 4379, 'name': 'time travel'}, {'id': 5...",Men in Black 3,52.035179,2012-05-23,6.2,4160,Will Smith,Tommy Lee Jones,Josh Brolin,[Barry Sonnenfeld],"[Walter F. Parkes, Laurie MacDonald]","[Wayne Wahrman, Don Zimmerman]"
19,"[Action, Adventure, Fantasy]","[{'id': 417, 'name': 'corruption'}, {'id': 603...",The Hobbit: The Battle of the Five Armies,120.965743,2014-12-10,7.1,4760,Martin Freeman,Ian McKellen,Richard Armitage,[Peter Jackson],"[Peter Jackson, Fran Walsh, Carolynne Cunningh...",[Jabez Olssen]